CREATE TABLE IF NOT EXISTS TASK (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
header VARCHAR(50) NOT NULL,
description VARCHAR(100) NOT NULL,
transactionDate DATE NOT NULL,
taskType VARCHAR(10) NOT NULL
);
